pipelines:
  branches:
   main:
    - step:
        name: build
        image: node:18.19.0-slim
        caches:
          - node
        script:
          - npm install
          - npm run build
          - cp -R staticwebapp.config.json dist/
        artifacts:
          - dist/**
    - step:
        name: Deploy to test
        deployment: test
        script:
          - chown -R 165536:165536 $BITBUCKET_CLONE_DIR
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/dist'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR'
                API_TOKEN: $deployment_token